### ISSUE TITLE
Plugin Crash's in CLion - Linux

### ISSUE THREAD

**Issue by konradx64** [conan-io/conan-clion-plugin#166]
Hello, 
I use the conan clion plugin for some time on windows, today I wanted to test it on linux but had to realize that when I press on the icon for conan it opens a window in which but says "nothing to show" and at the same time I get the following error message from CLion displayed:

> com.intellij.diagnostic.PluginException: Cannot init toolwindow com.jfrog.conan.clion.toolWindow.ConanWindowFactory@6aed1384 [Plugin: com.jfrog.conan.clion]
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.registerToolWindows(ToolWindowSetInitializer.kt:191)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.access$registerToolWindows(ToolWindowSetInitializer.kt:1)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1$1.invoke(ToolWindowSetInitializer.kt:129)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1$1.invoke(ToolWindowSetInitializer.kt:121)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:248)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:199)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1.invokeSuspend(ToolWindowSetInitializer.kt:121)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:193)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ExceptionInInitializerError
	at com.jfrog.conan.clion.toolWindow.ReadmePanel.<init>(ReadmePanel.kt:15)
	at com.jfrog.conan.clion.toolWindow.PackageInformationPanel.<init>(PackageInformationPanel.kt:28)
	at com.jfrog.conan.clion.toolWindow.ConanWindowFactory$ConanWindow.<init>(ConanWindowFactory.kt:43)
	at com.jfrog.conan.clion.toolWindow.ConanWindowFactory.createToolWindowContent(ConanWindowFactory.kt:34)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:554)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:533)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:1014)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:951)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl$default(ToolWindowManagerImpl.kt:937)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1121)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.registerToolWindows(ToolWindowSetInitializer.kt:181)
	... 43 more
Caused by: java.lang.IllegalStateException: JCEF is not supported in this env or failed to initialize
	at com.intellij.ui.jcef.JBCefApp.getInstance(JBCefApp.java:120)
	at com.intellij.ui.jcef.JCEFHtmlPanel.<clinit>(JCEFHtmlPanel.java:17)
	... 54 more
>
I can't do much with it, but further down it says something about "com.jfrog.conan"

Arch Linux
CLion: 2023.2.2
openjdk 20.0.2 2023-07-18
OpenJDK Runtime Environment (build 20.0.2+9)
OpenJDK 64-Bit Server VM (build 20.0.2+9, mixed mode, sharing)

**Comment by czoido** [comment]
Hi @knimix,

I think maybe the problem is that something failed while fetching the list of packages, If there's a rounded arrows button (update button), could you please click on it, like this:

![image](https://github.com/conan-io/conan-clion-plugin/assets/5045666/6d88c18f-e23e-444e-9155-65851b16845f)

After that, maybe the list of packages will appear again. If it does not, can you please try to reinstall the plugin?

Thanks a lot!

**Comment by konradx64** [comment]
@czoido 
Hello,
 no that does not work. I really have nothing in my window, no search bar, no buttons, just the text "nothing to show". I can't take a screenshot because I don't have my current Linux PC. I only know that the window for the Conan plugin is completely empty and the IDE gives me an error when I press on the icon (so try to open the window).

**Comment by czoido** [comment]
> @czoido Hello, no that does not work. I really have nothing in my window, no search bar, no buttons, just the text "nothing to show". I can't take a screenshot because I don't have my current Linux PC. I only know that the window for the Conan plugin is completely empty and the IDE gives me an error when I press on the icon (so try to open the window).

Hi @knimix,
Thanks a lot, did you already try to re-install the plugin?

**Comment by konradx64** [comment]
@czoido 
Of course, I only open an issue after I have already done everything possible (reinstalled CLion, reinstalled plugin, general updates, (don't worry graphics driver is up to date), etc.). 
I thought the error message would help

**Comment by czoido** [comment]
@knimix
Ok, we will try to do our best to reproduce this. Could you please confirm wether you installed CLion via pacman or manually downloading from JetBrains?
Also, a screen capture would be helpful if that's possible at some point.
Thanks

**Comment by uilianries** [comment]
Hello @knimix 

Which Arch Linux version are you running? Is it real Arch Linux or another distro like Manjaro?

**Comment by konradx64** [comment]
Hi @czoido 

Unfortunately, I can only take an original screenshot at the end of the week, as I don't currently have my Linux PC, but I have recreated what it looks like using the image you sent
![Unbenannt](https://github.com/conan-io/conan-clion-plugin/assets/68194543/6cba2f5b-1dc2-480d-b848-a11337894eab)

plus a red popup from CLion with an error that I wrote in the post at the beginning.

I use Clion from AUR, which corresponds to the latest version CLion: 2023.2.2

**Comment by konradx64** [comment]
> Hello @knimix
> 
> Which Arch Linux version are you running? Is it real Arch Linux or another distro like Manjaro?

I wrote that I use Arch Linux, so I use Arch linux. 
I also wrote that I only open an issue after I have updated the system (also reinstalling clion etc...), so yes, I use the latest version.

**Comment by uilianries** [comment]
@knimix I was able to reproduce your error, but only when running Clion with OpenJDK:

![using_openjdk_20](https://github.com/conan-io/conan-clion-plugin/assets/4870173/ceb5e812-df65-48fa-9230-dd028e5211dc)

As you can see, the conan window is showing "Nothing to show" and the log shows the same `Caused by: java.lang.IllegalStateException: JCEF is not supported in this env or failed to initialize` message.

The Clion when installed directly from Jetbrains [download page](https://www.jetbrains.com/clion/download) it comes with an embedded JDK that's the recommended by Jetbrains and it works with Conan plugin.

However, when installing from [AUR](https://aur.archlinux.org/packages/clion), the CLion's JRE is not installed automatically, but showed as recommend package when installing Clion. Thus, it should be installed as the separated package [clion-jre](https://aur.archlinux.org/packages/clion-jre). 

Note that CLion has a warning message about not using other JDK that are not asked by Jetbrains' support, and it may cause unexpected behavior, just like yours:

![using_jetbrains_jre](https://github.com/conan-io/conan-clion-plugin/assets/4870173/0ec8c384-05a0-4492-90c7-f1d111039361)

Please, install `clion-jre` AUR package, and update JDK in your Clion to use Jetbrains' bundled JDK. You can follow [this official tutorial](https://www.jetbrains.com/help/clion/switching-boot-jdk.html) to update Clion's JDK. Please, don't forget to restart your Clion IDE after updating the JDK, otherwise, it will not take effect.

Regards.

**Comment by konradx64** [comment]
@uilianries 
Thanks, I will test it tomorrow on my PC. That will probably be the solution, but I'll let you know if it works.

**Comment by konradx64** [comment]
Hi @uilianries ,
I have now uninstalled the openjdk and installed the clion-jre package, it works now.
Thanks for the effort.
