### ISSUE TITLE
Conan plugin's actions throw exceptions when conan executable isn't configured

### ISSUE THREAD

**Issue by Maririri** [conan-io/conan-clion-plugin#25]
- install Conan plugin
- click Install button

```stacktrace
Details: [com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:416), com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:51), com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:44), conan.commands.task.SyncConanTask.run(SyncConanTask.java:44), com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731), com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:442), com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164), com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586), com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532), com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86), com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151), com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:594), com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511), java.util.concurrent.FutureTask.run(FutureTask.java:266), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)]

java.lang.Throwable: Cannot run program "conan" (in directory "C:\Users\Maria.Baburina\ClionProjects\untitled34"): CreateProcess error=2, The system cannot find the file specified
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:162)
	at conan.utils.Utils.log(Utils.java:38)
	at conan.commands.task.SyncConanTask.run(SyncConanTask.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:594)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

- click 'Clean console' action

```stacktrace
java.lang.NullPointerException
	at conan.ui.ConanToolWindow.cleanConsole(ConanToolWindow.java:160)
	at conan.actions.CleanConsole.actionPerformed(CleanConsole.java:24)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:260)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:277)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:183)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:147)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:415)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:747)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:692)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by yahavi** [comment]
@Maririri Thanks.
Currently, this plugin [supports only running Conan from path](https://github.com/conan-io/conan-clion-plugin#prerequisites).

**Comment by Maririri** [comment]
@yahavi regarding running Conan from the path, I have Windows and macOS both of them contain Conan in the PATH (and it can be run from cmd). However, the plugin still shows me "Could not find Conan client in path", until I create a profile or invoke some action. This is misleading.

**Comment by lasote** [comment]
Hi, @Maririri I've open #26 with some improvements including fixing this. Now the path to Conan can be configured and the errors are no longer appearing even if the plugin is not locating the conan executable. 
Thanks for the feedback!

**Comment by Maririri** [comment]
the exceptions are still present in 1.2.0 version
I use conan from PATH.

**Comment by lasote** [comment]
Could you paste the traces or screenshot? Thanks

**Comment by jgsogo** [comment]
Hi, @Maririri 

I'm having a look to this issue and it looks like that we are catching the exception, but we are logging it to the `logger` and later in the `Notifications.Bus.notify` 

https://github.com/conan-io/conan-clion-plugin/blob/2b5e9664097c8f6707a235401f58925816c3a246/src/main/java/conan/utils/Utils.java#L50

As a consequence, the message appears in the "Event log" and also in the "Task bar" at the bottom. **I'm changing the message to provide a nicer message.**

I would like to know if there is a better approach to call Conan, but the docs for Intellij SDK are under construction and I cannot find more information.

Thanks
